services:
  api-bad:
    build:
      context: ./api-bad
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./db/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test: ["CMD", "mysql", "-hlocalhost", "-uuser", "-ppassword", "-e", "USE demo;"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  prometheus:
    image: prom/prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  k6:
    build: ./k6
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - K6_OUT=xk6-prometheus-rw
    command: ["run", "-o", "xk6-prometheus-rw", "/home/k6/loadtest.js"]

  prom_mysql_exporter:
    image: prom/mysqld-exporter
    ports:
      - '9104:9104'
    environment:
      DATA_SOURCE_NAME: user:password@(db:3306)/demo
    volumes:
      - ./db/config.my.cnf:/.my.cnf
    depends_on:
      db:
        condition: service_healthy