global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mysql
    static_configs:
      - targets: ['prom_mysql_exporter:9104']
        labels:
          alias: mysql

  - job_name: api
    static_configs:
      - targets: ['api-bad:8080']
        labels:
          alias: api